- name: Install dependencies
  apt:
    name: screen
    state: present
    update_cache: yes

- name: Copy nexus_multi.sh file
  copy:
    src: nexus_multi.sh
    dest: /root/nexus_multi.sh
    mode: "0755"

- name: Run Nexus script with automated setup
  shell: |
    export AUTO_MODE=1
    export NODE_COUNT=1
    export THREADS_PER_NODE={{ threads }}
    export NODE_ID={{ node_id }}
    /root/nexus_multi.sh
  args:
    executable: /bin/bash
  register: nexus_output

- name: Debug output
  debug:
    var: nexus_output.stdout_lines
