- name: Install dependencies
  apt:
    name: screen
    state: present
    update_cache: yes

- name: Copy nexus_multi.sh file
  copy:
    src: nexus_multi.sh
    dest: /root/nexus_multi.sh
    mode: "0755"

- name: Run Nexus script with automated setup
  expect:
    command: /root/nexus_multi.sh
    responses:
      "Select option:": "1"
      "How many nodes do you want to run.*": "1"
      "Threads per node.*": "{{ threads }}"
      "NodeID 1:": "{{ node_id }}"
      "Continue anyway.*": "y"
    timeout: 300
  register: nexus_output

- name: Debug output
  debug:
    var: nexus_output.stdout_lines
